apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ttrbui441-python 
  janus-idp.io/tekton: ttrbui441-python
  backstage.io/kubernetes-id: ttrbui441-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ttrbui441-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml