apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ttrbui441-python
  janus-idp.io/tekton: ttrbui441-python
  backstage.io/kubernetes-id: ttrbui441-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ttrbui441-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
