apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ttrbui441-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ttrbui441-python 
  name: ttrbui441-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ttrbui441-python 
